
services:
  # -------------- Database ------------------------------------------
  postgres:
    image: postgres:15-alpine
    container_name: voting-db
    environment:
      POSTGRES_DB: votingapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql/:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - voting-network
    
  # -------------- Backend ------------------------------------------
  backend:
    build:
      context: ./backend
      target: development
    container_name: voting-backend
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: votingapp
      DB_USER: postgres
      DB_PASSWORD: postgres
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - voting-network
    restart: unless-stopped

  # -------------- Volume ------------------------------------------

volumes:
  postgres_data: 

  # -------------- Networks ------------------------------------------
networks:
  voting-network:
    driver: bridge
      